[application]

# App (Project) Name
name = "img_viewer"

[web.app]

# HTML title tag content
title = "img_viewer"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.dm"
publisher = "MyCompany"
# The list of files to include in the bundle. These can contain globs.
resources = ["assets\\main.css"]
icon = ["icons\\icon48.png"]
